add_library(nodes 
node.h
system_functions.h system_functions.cpp
operation_nodes.h operation_nodes.cpp
variable_node.h variable_node.cpp
assignment_node.h assignment_node.cpp
for_node.h for_node.cpp
while_node.h while_node.cpp
function_definition_node.h function_definition_node.cpp
if_node.h if_node.cpp
primitive_nodes.h primitive_nodes.cpp
func_variable_node.h func_variable_node.cpp
break_continue_nodes.h break_continue_nodes.cpp
)